### ISSUE TITLE
Enable the use of Reserved Internal IP's

### ISSUE THREAD

**Issue by ralphpi** [citrix/citrix-adc-gdm-templates#1]
Looking through the config yml it doesn't there is any ability to utilize an already reserved internal IP or External IP for this deployment. 
 
Perhaps something like 

``` 
imports:
- path: template.py
resources:
- name: citrix-adc-2nic-deployment
  type: template.py
  properties:
   #The Google Region where the Citrix ADC would be deployed. Example: us-east1
   region: "<region>"
   #The availability zone in the region where the Citrix ADC would be deployed.
   #Example: us-east1-b
   google_zone: "<google_zone>"
   #The network to deploy the Citrix ADC
   mgmt_network: "<management_network>"
   #Subnet for the management interface
   mgmt_subnet: "<management_subnet>"


   #Reserved Internal IP
   reserved_internal_ip: "<reserved_internal_ip_name>"
   #Reserved External IP
   reserved_external_ip: "<reserved_external_ip_name>"

   #Ports to open to process management traffic
   mgmt_ports:
       - "22"
       - "80"
       - "443"
   #Network for the nic used to handle client/server side traffic
   traffic_network: "<traffic_network>"
   #Subnet in the specified network to handle client/server side traffic
   traffic_subnet: "<traffic_subnet>"
   #Ports to open to process client/server traffic
   traffic_ports:
       - "80"
       - "22"
   #The Citrix ADC image name
   image_name: "<image_name>"
   #The project name where the image is hosted
   image_project_id: "<image_project_id>"
   #The instance type to deploy the Citrix ADC instance Example: n1-standard-4
   instance_type: "<instance_type>"
   #The public key used for authenticating into the Citrix ADC.
   #Specify values separated by \n to specify more than one user.
   #Set it to "" if you wish to specify no key
   ssh_public_key: "[USERNAME_1]:ssh-rsa [EXISTING_KEY] [USERNAME_1]"
   #Specify a service account. If not, leave the field blank.
   service_account: "<service_account>"
   #Enter "yes" if you would like a public ip to be associated to the NIC.
   assign_public_ip: "<yes/no>"
```
